### ISSUE TITLE
persisting plugin panel position in application layout

### ISSUE THREAD

**Issue by agerardin** [agerardin/joplin-plugin-knowledge-graph#12]
Also a very annoying issue with setting "don't show graph on startup" is that the position of the panel is reset whenever Joplin restarts. This means that every time I start Joplin I have to rearrange and resize all my panels which isn't an insignificant amount of time. This needs to be fixed before that setting is usable for me.

_Originally posted by @shbach in https://github.com/agerardin/joplin-plugin-knowledge-graph/issues/5#issuecomment-1007008039_

**Comment by agerardin** [comment]
Ok the feature seems to be mentioned here :

https://discourse.joplinapp.org/t/changing-the-application-layout-in-v1-4/13073

**Comment by shbach** [comment]
Yes, that's the panel positioning I was referring to. I like to have the graph panel in the middle under the editor and toggle it on and off in that location. The default placement for new panels is on the the far right of existing panels. Having the graph panel be placed there is not usable because it will be too narrow.

**Comment by agerardin** [comment]
As I suspected, the Joplin application layout is not working properly whenever the graph panel is created after the plugin registration. Release v1.1.0 solves this.
